<MenuWidget>:
    canvas.before:
        Color:
            rgba: 0,0,0,.8
        Rectangle:
            size: self.size
    Label:
        font_size: dp(60)
        text: root.parent.menuTitle
        font_name: "fonts/Sackers-Gothic-Std-Light.ttf"
        pos_hint: { "center_x":.5, "center_y": .6}
    Button:
        text: root.parent.buttonTitle
        font_size: dp(30)
        font_name: "fonts/Eurostile.ttf"
        pos_hint: { "center_x":.5, "center_y": .3}
        size_hint: .2,.15
        on_press: root.parent.onMenuButtonPressed()
        background_normal: ''
        background_color: 1,.3,.4,.85